# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rr0kl8j2sYOVTpPgLt1BfQjyPaz0yXwZ
"""

from google.colab import drive
drive.mount('/content/drive')

train_path="/content/drive/My Drive/train"
file = 'drive/My Drive/train/Train_dataset.xlsx'

import pandas as pd
df=pd.read_excel(file)
df.head()

df.tail()

import seaborn as sns

Var_Corr = df.corr()
# plot the heatmap and annotation on it
sns.heatmap(Var_Corr, xticklabels=Var_Corr.columns, yticklabels=Var_Corr.columns, annot=True)

df1=df.drop(['people_ID','Name','Designation','Married','Children','salary'],axis=1)
df1.head()

one_hot = pd.get_dummies(df1['Region'])
df1 = df1.drop('Region',axis = 1)
df1 = df1.join(one_hot)

one_hot = pd.get_dummies(df1['Gender'])
df1 = df1.drop('Gender',axis = 1)
df1 = df1.join(one_hot)

one_hot = pd.get_dummies(df1['Mode_transport'])
df1 = df1.drop('Mode_transport',axis = 1)
df1 = df1.join(one_hot)

one_hot = pd.get_dummies(df1['comorbidity'])
df1 = df1.drop('comorbidity',axis = 1)
df1 = df1.join(one_hot)

one_hot = pd.get_dummies(df1['cardiological pressure'])
df1 = df1.drop('cardiological pressure',axis = 1)
df1 = df1.join(one_hot)

df1.head()

one_hot = pd.get_dummies(df1['Pulmonary score'])
df1 = df1.drop('Pulmonary score',axis = 1)
df1 = df1.join(one_hot)

one_hot = pd.get_dummies(df1['Occupation'])
df1 = df1.drop(['Occupation','Insurance'],axis = 1)
df1 = df1.join(one_hot)

df1.head()

df1=df1[['cases/1M','Deaths/1M','Age','Coma score','Diuresis','Platelets','HBB','d-dimer','Heart rate','HDL cholesterol','Charlson Index','Blood Glucose','FT/month','Bengaluru','Bhubaneshwar','Chandigarh','Chennai','Delhi','Female','Male','Car','Public','Walk','Coronary Heart Disease','Diabetes','Hypertension','None','Elevated','Normal','Stage-01','Stage-02','<100','<200','<300','<400','Business','Cleaner','Clerk','Driver','Farmer','Legal','Manufacturing','Researcher','Sales','Infect_Prob']]

df1=df1.drop(['Bengaluru','Bhubaneshwar','Chandigarh','Chennai','Delhi'],axis=1)



import numpy as np
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

clean_dataset(df1)

X=df1.iloc[:,:-1]
Y=df1.iloc[:,-1]
from sklearn.svm import SVR
clf = SVR(kernel='rbf')
clf.fit(X,Y)

X.shape[1]

test_path="/content/drive/My Drive/test"
file = 'drive/My Drive/test/Test_dataset.xlsx'
df2=pd.read_excel(file)
df2.head()

df2=df2.drop(['people_ID','Name','Designation','Married','Children','salary'],axis=1)

one_hot = pd.get_dummies(df2['Region'])
df2 = df2.drop('Region',axis = 1)
df2 = df2.join(one_hot)
one_hot = pd.get_dummies(df2['Gender'])
df2 = df2.drop('Gender',axis = 1)
df2 = df2.join(one_hot)
one_hot = pd.get_dummies(df2['Mode_transport'])
df2 = df2.drop('Mode_transport',axis = 1)
df2 = df2.join(one_hot)
one_hot = pd.get_dummies(df2['comorbidity'])
df2 = df2.drop('comorbidity',axis = 1)
df2 = df2.join(one_hot)
one_hot = pd.get_dummies(df2['cardiological pressure'])
df2 = df2.drop('cardiological pressure',axis = 1)
df2 = df2.join(one_hot)
one_hot = pd.get_dummies(df2['Pulmonary score'])
df2 = df2.drop('Pulmonary score',axis = 1)
df2 = df2.join(one_hot)
one_hot = pd.get_dummies(df2['Occupation'])
df2 = df2.drop(['Occupation','Insurance'],axis = 1)
df2 = df2.join(one_hot)

df2=df2.drop(['Delhi','Hyderabad','Kolkata','Mumbai','Pune','Thiruvananthapuram'],axis=1)

clean_dataset(df2)

X_test=df2.iloc[:,:]
X_test.shape[1]

y_pred=clf.predict(X_test)
df4=pd.DataFrame(y_pred)
df4

df3=pd.read_excel(file)
df3=df3.iloc[:,0]
df3

frames=[df3, df4]
result=pd.concat(frames,axis=1)
result.columns=['people_ID','Infect_prob']
result.to_excel("task1.xlsx")